---
- name: /etc/network/interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify:
    - reboot

- name: /etc/modules-load.d/modules.conf
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: vhost_net
    state: present
  notify:
    - reboot
