---
# /etc/systemd/logind.conf:
# ...
# HandleLidSwitch=ignore
# HandleLidSwitchExternalPower=ignore
# HandleLidSwitchDocked=ignore
# ...

- name: /etc/systemd/logind.conf HandleLidSwitch
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: 'HandleLidSwitch'
    line: 'HandleLidSwitch=ignore'

- name: /etc/systemd/logind.conf HandleHandleLidSwitchExternalPowerLidSwitch
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: 'HandleLidSwitchExternalPower'
    line: 'HandleLidSwitchExternalPower=ignore'

- name: /etc/systemd/logind.conf HandleLidSwitchDocked
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: 'HandleLidSwitchDocked'
    line: 'HandleLidSwitchDocked=ignore'

# TODO: restart systemd-logind.service if changed