---
- name: locale set
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: locale get current
  command: localectl status
  register: locale_status
  changed_when: false

- name: parse 'LANG' from current locale
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: locale set default
  command: localectl set-locale en_US.UTF-8
  changed_when: locale_lang != "en_US.UTF-8"

